.TH MYSTRLEN 3 "September 2026" "Version 1.0" "MyUtils Programmer's Manual"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.br
.BI "int mystrlen(const char *" s ");"
.SH DESCRIPTION
The 
.B mystrlen()
function calculates the length of the string 
.I s
pointed to, excluding the terminating null byte ('\\0').
.SH AUTHOR
Ayesha
